on load:
    load yaml "plugins/SecurityAlert/config.yml" as "config"
    set {mfont} to yml value "customization.primary-color" from "config"
    set {sfont} to yml value "customization.secondary-color" from "config"
every 1 second:
    loop all players:
        if loop-player has scoreboard tag "elevators":
            set {vators} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Plex &5Elevators"
            set slot 12 of {vators} to iron block named "Atrium left"
            set slot 13 of {vators} to emerald block named "Entrance"
            set slot 14 of {vators} to gold block named "Atrium right"
            set slot 22 of {vators} to barrier named "&cClose"
            open {vators} to loop-player
            remove "elevators" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "vendingmachineuse":
            set {vending} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Plex &5Vending machine"
            set slot 12 of {vending} to potion named "&dFur Purr" with lore "&dMade with extra cream for that extra boost!"
            set slot 14 of {vending} to potion named "&6Furenta" with lore "&fThe best furry booze in the &6FurPlex"
            set slot 22 of {vending} to barrier named "&cClose"
            open {vending} to loop-player
            remove "vendingmachineuse" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "RACECONTROL":
            set {rcontrol} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Plex &5Raceway Controller"
            set slot 12 of {rcontrol} to black wool named "&cWelcome To The Racetrack"
            set slot 14 of {rcontrol} to lime wool named "&aStart Race"
            set slot 22 of {rcontrol} to barrier named "&cClose"
            open {rcontrol} to loop-player
            remove "RACECONTROL" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "FURDJ":
            set {DJinv} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%DJ Menu"
            set slot 10 of {DJinv} to twisting vines named "&3The Wave" with lore "&fMakes a wave patern that goes from Right to Left"
            set slot 11 of {DJinv} to tnt named "&cThe Explosion" with lore "&fExplosive kind of movement, that makes it go &cBOOM"
            set slot 12 of {DJinv} to iron sword named "&fNinja" with lore "&fNinja kind of weapon, with a light full twist"
            set slot 13 of {DJinv} to ender pearl named "&3The Ripple" with lore "&fCircle animation of the &3Water &fwith circles"
            set slot 14 of {DJinv} to hopper named "&fThe Dropper" with lore "&fFalling down and down, faster and faster until hiting something..."
            set slot 15 of {DJinv} to fire charge named "&cTerminate" with lore "&fKill the target..."
            set slot 16 of {DJinv} to redstone lamp named "&cOff" with lore "&fTurn the Lights off!"
            set slot 22 of {DJinv} to barrier named "&cClose"
            set slot 23 of {DJinv} to arrow named "&aNext Page"
            open {DJinv} to loop-player
            remove "FURDJ" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "FURMUSIC":
            set {MUSICinv} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Music"
            set slot 11 of {MUSICinv} to pink concrete named "&dJoin us for a bite - JT Music" with lore "&fSister Location Remix, where she will consume u..."
            set slot 12 of {MUSICinv} to light blue concrete named "%{sfont}%Fur%{mfont}%Plex Main Theme" with lore "&fThe Main rocking theme of the %{sfont}%Fur%{mfont}%Plex"
            set slot 13 of {MUSICinv} to red concrete named "&cFive Night's at FurPlex" with lore "&fFive Night's at our home, our place and our rules..."
            set slot 14 of {MUSICinv} to purple concrete named "&5It's been so long" with lore "&fThe slaughter house between the Arcades of the Plex..."
            set slot 15 of {MUSICinv} to lime concrete named "&aWonderwall" with lore "&fToday is gonna be the day... bitch"
            set slot 21 of {MUSICinv} to arrow named "&aPrevious Page"
            set slot 22 of {MUSICinv} to barrier named "&cClose"
            set slot 23 of {MUSICinv} to note block named "&cStop Sounds"
            open {MUSICinv} to loop-player
            remove "FURMUSIC" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "FURSPEAKERCONTROL":
            set {SPEAKERinv} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Speaker&5Control"
            set slot 10 of {SPEAKERinv} to blue concrete named "&cFreddy - CG5/Matpat etc." 
            set slot 11 of {SPEAKERinv} to pink concrete named "&dJoin us for a bite - JT Music" 
            set slot 12 of {SPEAKERinv} to light blue concrete named "%{sfont}%Fur%{mfont}%Plex Main Theme"
            set slot 13 of {SPEAKERinv} to red concrete named "&cFive Night's at Freddy's"
            set slot 14 of {SPEAKERinv} to purple concrete named "&5It's been so long"
            set slot 15 of {SPEAKERinv} to lime concrete named "&aWonderwall"
            set slot 16 of {SPEAKERinv} to black concrete named "&aDancing in the moonlight" 
            set slot 22 of {SPEAKERinv} to barrier named "&cClose"
            set slot 23 of {SPEAKERinv} to note block named "&cStop Sounds"
            open {SPEAKERinv} to loop-player
            remove "FURSPEAKERCONTROL" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "elevator":
            set {Elevinv} to chest inventory with 3 rows named "%{sfont}%&lElevator"
            set slot 11 of {Elevinv} to light blue concrete named "%{mfont}%Entrance" with lore "&fWhere u enter the %{sfont}%Mega Fur%{mfont}%Plex&f!" and "" and "&fHere you have:" and "%{mfont}%- Fur&Stuff" and "%{mfont}%- Store Area" and "%{mfont}%- Mega Lounge" and "%{mfont}%- Exit" and "" and "%{mfont}%&lGround Floor"
            set slot 13 of {Elevinv} to pink concrete named "&dFur Plaza" with lore "&fFloor 1 of the Entrance Hall!" and "&fHere is located:" and "" and "%{sfont}%- FurMusic Restaurant" and "&d- FurCandy Island" and "&d- Atrium Access" and "" and "&d&l1st Floor"
            set slot 15 of {Elevinv} to gold block named "&6VIP & Prizecounter" with lore "&fPick up your price! Or go to &6VIP" with lore "&fThis area is where u can pickup" and "&fyour gained prices or items" and "&fHere you also have:" and "" and "&6- VIP Entrance" and "&6- Atrium Access" and "&6- Arcade Access" and "" and "&6&l2nd Floor"
            set slot 22 of {Elevinv} to barrier named "&cClose"
            open {Elevinv} to loop-player
            remove "elevator" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "A-Elevator-A":
            set {AelevA} to chest inventory with 3 rows named "%{sfont}%&lAtrium Elevator A"
            set slot 11 of {AelevA} to red concrete named "&c&lMain Floor" with lore "&fThe place where we have" and "&fall the Fursona attractions & shops!" and "&fHere you have:" and "&c- Main Stage" and "&c- Furrblast" and "&c- Superstar Kid's-cade" and "&c- FurRace" and "" and "&c&lMain Floor"
            set slot 13 of {AelevA} to light blue concrete named "%{mfont}%&lFur Plaza" with lore "&fThe main entrance of the Atrium" and "&ffrom the Lobby Entrance" and "&fHere is located:" and "" and "%{mfont}%- SuperFurr Daycare" and "%{mfont}%- EclipsCake Shoppe" and "%{mfont}%- Lobby Entrance" and "" and "%{mfont}%&l1st Floor"
            set slot 15 of {AelevA} to pink concrete named "&d&lFur Entertainment" with lore "&fPlay games, enjoy music & more!" with lore "&fThese parts of the Furplex" and "&fare located here:" and "" and "&d- FurCade" and "&d- FurBowling" and "&d- Prizecounter" and "&d- Superfurcade" and "&d- Furrycise" and "" and "&d&l2nd Floor"
            set slot 22 of {AelevA} to barrier named "&cClose"
            if loop-player has scoreboard tag "STAFFX":
                set slot 23 of {AelevA} to redstone block named "&c&lReset Elevator" with lore "&fSet the elevator to Floor 1" and "" and "&c&lWARNING USE THIS WITHOUT PASSENGERS"
            open {AelevA} to loop-player
            wait 5 ticks
            remove "A-Elevator-A" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "A-Elevator-B":
            set {AelevB} to chest inventory with 3 rows named "%{sfont}%&lAtrium Elevator B"
            set slot 11 of {AelevB} to red concrete named "&c&lMain Floor" with lore "&fThe place where we have" and "&fall the Fursona attractions & shops!" and "&fHere you have:" and "&c- Main Stage" and "&c- Furrblast" and "&c- Superstar Kid's-cade" and "&c- FurRace" and "" and "&c&lMain Floor"
            set slot 13 of {AelevB} to light blue concrete named "%{mfont}%&lFur Plaza" with lore "&fThe main entrance of the Atrium" and "&ffrom the Lobby Entrance" and "&fHere is located:" and "" and "%{mfont}%- SuperFurr Daycare" and "%{mfont}%- EclipsCake Shoppe" and "%{mfont}%- Lobby Entrance" and "" and "%{mfont}%&l1st Floor"
            set slot 15 of {AelevB} to pink concrete named "&d&lFur Entertainment" with lore "&fPlay games, enjoy music & more!" with lore "&fThese parts of the Furplex" and "&fare located here:" and "" and "&d- FurCade" and "&d- FurBowling" and "&d- Prizecounter" and "&d- Superfurcade" and "&d- Furrycise" and "" and "&d&l2nd Floor"
            set slot 22 of {AelevB} to barrier named "&cClose"
            if loop-player has scoreboard tag "STAFFX":
                set slot 23 of {AelevB} to redstone block named "&c&lReset Elevator" with lore "&fSet the elevator to Floor 1" and "" and "&c&lWARNING USE THIS WITHOUT PASSENGERS"
            open {AelevB} to loop-player
            wait 5 ticks
            remove "A-Elevator-B" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "FURPLEX":
            set {_inv} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Store"
            set slot 11 of {_inv} to paper named "%{mfont}%Tokens" with lore "&fThe main credit of the %{sfont}%Mega Fur%{mfont}%Plex&f, which u can exchange to here!"
            set slot 13 of {_inv} to armor stand named "%{mfont}%Staff" with lore "&fWant to be staff? Apply here!! Applications are currently %{staffr}%"
            set slot 15 of {_inv} to iron block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            set slot 22 of {_inv} to barrier named "&cClose"
            open {_inv} to loop-player
            remove "FURPLEX" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "DEPOTDIA":
            if {diagained} is 0:
                send "%{mfont}%There are no Diamonds to deposit currently!" to loop-player
                wait 5 ticks
                remove "DEPOTDIA" from the scoreboard tags of loop-player
            else:
                give {diagained} of diamond to loop-player
                send "%{mfont}%U got %{diagained}% Diamonds deposited to your inventory" to loop-player
                set {diagained} to 0
                wait 5 ticks
                remove "DEPOTDIA" from the scoreboard tags of loop-player
        while name of loop-player's current inventory is "%{sfont}%Fur%{mfont}%Store":
            set slot 11 of {_inv} to paper named "%{mfont}%Tokens" with lore "&fThe main credit of the %{sfont}%Mega Fur%{mfont}%Plex&f, which u can exchange to here!"
            set slot 15 of {_inv} to iron block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
            set slot 15 of {_inv} to gold block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
            set slot 11 of {_inv} to diamond named "%{mfont}%Tokens" with lore "&fThe main credit of the %{sfont}%Mega Fur%{mfont}%Plex&f, which u can exchange to here!"
            set slot 15 of {_inv} to diamond block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
            set slot 15 of {_inv} to netherite block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
        while name of loop-player's current inventory is "%{mfont}%FurToken ATM":
            set slot 15 of {ainv} to 20 of diamond named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!"
            set slot 11 of {ainv} to 2 of diamond named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!"
            wait 1 seconds
            set slot 11 of {ainv} to paper named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!"
            set slot 15 of {ainv} to 10 of paper named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!"
            wait 1 seconds
            
on inventory click:
    if name of event-inventory is "%{sfont}%Fur%{mfont}%Plex &5Vending machine":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        if event-item is potion named "&dFur Purr":
            add "VENDINGA" to the scoreboard tags of player
            wait 1 tick
            close event-player's inventory
        if event-item is potion named "&6Furenta":
            add "VENDINGB" to the scoreboard tags of player
            wait 1 tick
            close event-player's inventory
    else if name of event-inventory is "%{sfont}%Fur%{mfont}%Plex &5Elevators":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        if event-item is iron block named "Atrium left":
            add "A-Elevator-B" to the scoreboard tags of player
            wait 1 tick
            close event-player's inventory
        if event-item is gold block named "Atrium right":
            add "A-Elevator-A" to the scoreboard tags of player
            wait 1 tick
        if event-item is emerald block named "Entrance":
            add "elevator" to the scoreboard tags of player
            wait 1 tick
            close event-player's inventory
    else if name of event-inventory is "%{sfont}%Fur%{mfont}%Plex &5Raceway Controller":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        if event-item is black wool named "&cWelcome To The Racetrack":
            add "WelcomeTrack" to the scoreboard tags of player
            wait 1 tick
            close event-player's inventory
        if event-item is lime wool named "&aStart Race":
            add "StartRace" to the scoreboard tags of player
            wait 1 tick
            close event-player's inventory
    else if name of event-inventory is "%{sfont}%Fur%{mfont}%DJ Menu":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        if event-item is twisting vines:
            add "DJ1" to the scoreboard tags of player
        if event-item is tnt:
            add "DJ2" to the scoreboard tags of player
        if event-item is iron sword:
            add "DJ3" to the scoreboard tags of player
        if event-item is ender pearl:
            add "DJ4" to the scoreboard tags of player
        if event-item is hopper:
            add "DJ5" to the scoreboard tags of player
        if event-item is fire charge:
            add "DJ6" to the scoreboard tags of player
        if event-item is redstone lamp:
            add "DJ7" to the scoreboard tags of player
        if event-item is arrow:
            close event-player's inventory
            open {MUSICinv} to player
    else if name of event-inventory is "%{sfont}%Fur%{mfont}%Music":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        else if event-item is lime concrete:
            make player execute command "stopsound @a[distance=..15] player"
            make player execute command "playsound music_disc.11 player @a[distance=..15] ~ ~ ~ 0.7"
        else if event-item is pink concrete:
            make player execute command "stopsound @a[distance=..15] player"
            make player execute command "playsound music_disc.blocks player @a[distance=..15] ~ ~ ~ 0.69"
        else if event-item is light blue concrete:
            make player execute command "stopsound @a[distance=..15] player"
            make player execute command "playsound music_disc.cat player @a[distance=..15] ~ ~ ~ 0.8"
        else if event-item is red concrete:
            make player execute command "stopsound @a[distance=..15] player"
            make player execute command "playsound music_disc.strad player @a[distance=..15] ~ ~ ~ 1"
        else if event-item is purple concrete:
            make player execute command "stopsound @a[distance=..15] player"
            make player execute command "playsound music_disc.mall player @a[distance=..15] ~ ~ ~ 0.7"
        else if event-item is note block:
            make player execute command "stopsound @a[distance=..15] player"
        else if event-item is arrow:
            close event-player's inventory
            open {DJinv} to event-player
    else if name of event-inventory is "%{sfont}%Fur%{mfont}%Speaker&5Control":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        else if event-item is lime concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.11 player @s"
        else if event-item is pink concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.blocks player @s"
        else if event-item is light blue concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.cat player @s"
        else if event-item is red concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.strad player @s"
        else if event-item is purple concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.mall player @s"
        else if event-item is black concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.far player @s"
        else if event-item is blue concrete:
            make console execute command "execute as @a at @s run stopsound @s player"
            make console execute command "execute as @a at @s run playsound music_disc.ward player @s"
        else if event-item is note block:
            make console execute command "execute as @a at @s run stopsound @s player"
on load:
    set {furtoken} to paper named "&dFur%{mfont}%Token" with lore "&fMain credit of the &dMega Fur%{mfont}%Plex&f! U can use this to buy and sell!"
    set {vippass} to paper named "&l&6VIP Pass" with lore "&6VIP Access &fto the whole FurPlex!"
    set {famouspass} to paper named "&l%{mfont}%Famous Pass" with lore "%{mfont}%Famous Access &fto the whole FurPlex!"
every 1 seconds:
    loop all players:
        add 1 to {loops.%loop-player%}
        if loop-player has scoreboard tag "FURPLEX":
            set {_inv} to chest inventory with 3 rows named "%{sfont}%Fur%{mfont}%Store"
            set slot 11 of {_inv} to paper named "%{mfont}%Tokens" with lore "&fThe main credit of the %{sfont}%Mega Fur%{mfont}%Plex&f, which u can exchange to here!"
            set slot 13 of {_inv} to armor stand named "%{mfont}%Staff" with lore "&fWant to be staff? Apply here!! Applications are currently %{staffr}%"
            set slot 15 of {_inv} to iron block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            set slot 22 of {_inv} to barrier named "&cClose"
            open {_inv} to loop-player
            remove "FURPLEX" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "DEPOTDIA":
            if {diagained} is 0:
                send "%{mfont}%There are no Diamonds to deposit currently!" to loop-player
                wait 5 ticks
                remove "DEPOTDIA" from the scoreboard tags of loop-player
            else:
                give {diagained} of diamond to loop-player
                send "%{mfont}%U got %{diagained}% Diamonds deposited to your inventory" to loop-player
                set {diagained} to 0
                wait 5 ticks
                remove "DEPOTDIA" from the scoreboard tags of loop-player
        while name of loop-player's current inventory is "%{sfont}%Fur%{mfont}%Store":
            set slot 11 of {_inv} to paper named "%{mfont}%Tokens" with lore "&fThe main credit of the %{sfont}%Mega Fur%{mfont}%Plex&f, which u can exchange to here!"
            set slot 15 of {_inv} to iron block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
            set slot 15 of {_inv} to gold block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
            set slot 11 of {_inv} to diamond named "%{mfont}%Tokens" with lore "&fThe main credit of the %{sfont}%Mega Fur%{mfont}%Plex&f, which u can exchange to here!"
            set slot 15 of {_inv} to diamond block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
            set slot 15 of {_inv} to netherite block named "%{mfont}%Ranks" with lore "&fWe got custom ranks in the %{sfont}%Fur%{mfont}%Plex&f for visitors and others! View them here!"
            wait 1 seconds
        while name of loop-player's current inventory is "%{mfont}%FurToken ATM":
            set slot 15 of {ainv} to 20 of diamond named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!"
            set slot 11 of {ainv} to 2 of diamond named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!"
            wait 1 seconds
            set slot 11 of {ainv} to paper named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!"
            set slot 15 of {ainv} to 10 of paper named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!"
            wait 1 seconds
on inventory click:
    if name of event-inventory is "%{sfont}%Fur%{mfont}%Store":
        cancel event
        if event-item is barrier:
            close event-player's inventory
        if event-item is iron block, diamond block, gold block or netherite block:
            close event-player's inventory
            set {_inv} to chest inventory with 3 rows named "%{mfont}%Ranks"
            set slot 10 of {_inv} to iron block named "&fVisitor" with lore "&fSomeone who comes here and visits!" and "" and "&f- Access to Store & Lounge" and "&f- Access to Basic Fur&Stuff storage" and "&f- Atrium Access" and "&f- 1 Free Plush" and "" and "%{mfont}%&lFree"
            set slot 12 of {_inv} to gold block named "&6VIP" with lore "&fSpecial access to more entertaining for a more entertaining experience!" and "" and "&f- Access to VIP Area" and "&f- Premium Fur&Stuff Storage" and "&f-Free Drinks & Food" and "&f- 5 Free Assorties for your home" and "&6- VIP Pass" and "" and "&6&l150 FurTokens"
            set slot 14 of {_inv} to diamond block named "%{mfont}%Famous" with lore "&fAccess for famous people who are well known!" and "" and "&f- Access to ALL of the FurPlex" and "&f- Unlimited Fur&Stff Storage" and "&fFree FurPack" and "&f- Free Founder Tour" and "" and "%{mfont}%&lInvite Only"
            set slot 16 of {_inv} to netherite block named "&fFounder" with lore "&fFounder of the Mega FurPlex!" and "&fGot all permissions!" and "" and "&f&lFOUNDERS ONLY"
            set slot 22 of {_inv} to barrier named "&cClose"
            open {_inv} to player
        if event-item is diamond or paper:
            close event-player's inventory
            set {ainv} to chest inventory with 3 rows named "%{mfont}%FurToken ATM"
            set slot 11 of {ainv} to paper named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!"
            set slot 15 of {ainv} to 10 of paper named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!"
            set slot 22 of {ainv} to barrier named "&cClose"
            open {ainv} to player
    else if name of event-inventory is "%{mfont}%FurToken ATM":
        cancel event
        if event-item is barrier:
            close event-player's inventory
        if event-item is 1 of paper named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!":
            if event-player has 2 diamond:
                add 2 to {diagained}
                remove 2 of diamond from event-player
                give 1 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
        else if event-item is 10 of paper named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!":
            if event-player has 20 diamond:
                add 20 to {diagained}
                remove 20 of diamond from event-player
                give 10 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
        else if event-item is 20 of diamond named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!":
            if event-player has 20 diamond:
                add 20 to {diagained}
                remove 20 of diamond from event-player
                give 10 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
        else if event-item is 2 of diamond named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!":
            if event-player has 2 diamond:
                add 2 to {diagained}
                remove 2 of diamond from event-player
                give 1 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
    else if name of event-inventory is "%{mfont}%Ranks":
        cancel event
        if event-item is barrier:
            close event-player's inventory
        if event-item is gold block:
            if player has 150 of {furtoken}:
                close event-player's inventory
                set {arsinv} to chest inventory with 3 rows named "&fAre you sure?"
                set slot 11 of {arsinv} to green stained glass block named "&aYes"
                set slot 15 of {arsinv} to red stained glass block named "&cNo"
                open {arsinv} to event-player
            else:
                send "&cYou don't have enough FurTokens!"
    else if name of event-inventory is "&fAre you sure?":
        cancel event
        if event-item is red stained glass block:
            close event-player's inventory
        else if event-item is green stained glass block:
            remove 150 of {furtoken} from event-player
            add "VIP" to scoreboard tags of event-player
            close event-player's inventory
            send "&6You now have VIP!"
    else if name of event-inventory is "%{sfont}%Fur%{mfont}%Store":
        cancel event
        if event-item is barrier:
            close event-player's inventory
        if event-item is iron block, diamond block, gold block or netherite block:
            close event-player's inventory
            set {_inv} to chest inventory with 3 rows named "%{mfont}%Ranks"
            set slot 10 of {_inv} to iron block named "&fVisitor" with lore "&fSomeone who comes here and visits!" and "" and "&f- Access to Store & Lounge" and "&f- Access to Basic Fur&Stuff storage" and "&f- Atrium Access" and "&f- 1 Free Plush" and "" and "%{mfont}%&lFree"
            set slot 12 of {_inv} to gold block named "&6VIP" with lore "&fSpecial acces to more entertaining for a more entertaining experience!" and "" and "&f- Access to VIP Area" and "&f- Premium Fur&Stuff Storage" and "&f- Free Drinks & Food" and "&f- 5 Free Assorties for your home" and "&f- 25 procent Off everything!" and "&6- VIP Pass" and "" and "&6&l150 FurTokens"
            set slot 14 of {_inv} to diamond block named "%{mfont}%Famous" with lore "&fAccess for famous people who are well known!" and "" and "&f- Access to ALL of the FurPlex" and "&f- Unlimited Fur&Stff Storage" and "&fFree FurPack" and "&f- Free Founder Tour" and "&f- 50 procent Off everything!" and "" and "%{mfont}%&lInvite Only"
            set slot 16 of {_inv} to netherite block named "&fFounder" with lore "&fFounder of the Mega FurPlex!" and "&fGot all permissions!" and "" and "&f&lFOUNDERS ONLY"
            set slot 22 of {_inv} to barrier named "&cClose"
            open {_inv} to player
        if event-item is diamond or paper:
            close event-player's inventory
            set {ainv} to chest inventory with 3 rows named "%{mfont}%FurToken ATM"
            set slot 11 of {ainv} to paper named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!"
            set slot 15 of {ainv} to 10 of paper named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!"
            set slot 22 of {ainv} to barrier named "&cClose"
            open {ainv} to player
    else if name of event-inventory is "%{mfont}%FurToken ATM":
        cancel event
        if event-item is barrier:
            close event-player's inventory
        if event-item is 1 of paper named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!":
            if event-player has 2 diamond:
                add 2 to {diagained}
                remove 2 of diamond from event-player
                give 1 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
        else if event-item is 10 of paper named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!":
            if event-player has 20 diamond:
                add 20 to {diagained}
                remove 20 of diamond from event-player
                give 10 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
        else if event-item is 20 of diamond named "&f10 &dFur%{mfont}%Tokens" with lore "&fClick to trade!":
            if event-player has 20 diamond:
                add 20 to {diagained}
                remove 20 of diamond from event-player
                give 10 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
        else if event-item is 2 of diamond named "&f1 &dFur%{mfont}%Token" with lore "&fClick to trade!":
            if event-player has 2 diamond:
                add 2 to {diagained}
                remove 2 of diamond from event-player
                give 1 of {furtoken} to event-player
            else:
                close event-player's inventory
                send "&cYou don't have enough FurTokens!"
    else if name of event-inventory is "%{mfont}%Ranks":
        cancel event
        if event-item is barrier:
            close event-player's inventory
        if event-item is gold block:
            if player has 150 of {furtoken}:
                close event-player's inventory
                set {arsinv} to chest inventory with 3 rows named "&fAre you sure?"
                set slot 11 of {arsinv} to green stained glass block named "&aYes"
                set slot 15 of {arsinv} to red stained glass block named "&cNo"
                open {arsinv} to event-player
            else:
                send "&cYou don't have enough FurTokens!"
    else if name of event-inventory is "&fAre you sure?":
        cancel event
        if event-item is red stained glass block:
            close event-player's inventory
        else if event-item is green stained glass block:
            remove 150 of {furtoken} from event-player
            give 1 of {vippass} to event-player
            close event-player's inventory
            send "&6You now have VIP!"
            
on inventory click:
    if name of event-inventory is "%{sfont}%&lElevator":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        if event-item is light blue concrete:
            close event-player's inventory
            add "elevatorgroundfrom2ndfloor" to the scoreboard tags of player
            add "elevator3rdfromgroundopposite" to the scoreboard tags of player
        if event-item is pink concrete:
            close event-player's inventory
            add "elevatorsecondfloorfromfirst" to the scoreboard tags of player
            add "elevator3rdfrom2ndopposite" to the scoreboard tags of player
        if event-item is gold block:
            close event-player's inventory
            add "elevator3rdfromground" to the scoreboard tags of player
            add "elevator3rdfrom2nd" to the scoreboard tags of player
    else if name of event-inventory is "%{sfont}%&lAtrium Elevator A":
        cancel event
        if event-item is red concrete:
            close event-player's inventory
            add "A1-0" to the scoreboard tags of player
            add "A2-0" to the scoreboard tags of player
        if event-item is light blue concrete:
            close event-player's inventory
            add "A2-1" to the scoreboard tags of player
            add "A0-1" to the scoreboard tags of player
        if event-item is pink concrete:
            close event-player's inventory
            add "A1-2" to the scoreboard tags of player
            add "A0-2" to the scoreboard tags of player
        if event-item is redstone block:
            close event-player's inventory
            add "A-R" to the scoreboard tags of player
            wait 1 seconds
            make console execute command "tp %player% -1001 30 451"
        if event-item is barrier:
            close event-player's inventory
    else if name of event-inventory is "%{sfont}%&lAtrium Elevator B":
        cancel event
        if event-item is red concrete:
            close event-player's inventory
            add "B1-0" to the scoreboard tags of player
            add "B2-0" to the scoreboard tags of player
        if event-item is light blue concrete:
            close event-player's inventory
            add "B2-1" to the scoreboard tags of player
            add "B0-1" to the scoreboard tags of player
        if event-item is pink concrete:
            close event-player's inventory
            add "B1-2" to the scoreboard tags of player
            add "B0-2" to the scoreboard tags of player
        if event-item is redstone block:
            close event-player's inventory
            add "B-R" to the scoreboard tags of player
            wait 1 seconds
            make console execute command "tp %player% -1001 30 509"
        if event-item is barrier:
            close event-player's inventory           
