# ====---== FurPlex Functions File to make GUI's and interfaces! Recommended with the FurPlex World! ==---====
# This file is based on Tags, which u can view using /furplex tags list

options:
    furprefix: &d[Fur<##33A8FF>Plex]&f
    mfont: <##33A8FF>
    sfont: &d
    tfont: &f

#DJ Options Menu
every 1 seconds:
    loop all players:
        if loop-player has scoreboard tag "FURDJ":
            set {DJinv} to chest inventory with 3 rows named "{@sfont}Fur{@mfont}DJ Menu"
            set slot 10 of {DJinv} to twisting vines named "&3The Wave" with lore "&fMakes a wave patern that goes from Right to Left"
            set slot 11 of {DJinv} to tnt named "&cThe Explosion" with lore "&fExplosive kind of movement, that makes it go &cBOOM"
            set slot 12 of {DJinv} to iron sword named "&fNinja" with lore "&fNinja kind of weapon, with a light full twist"
            set slot 13 of {DJinv} to ender pearl named "&3The Ripple" with lore "&fCircle animation of the &3Water &fwith circles"
            set slot 14 of {DJinv} to hopper named "&fThe Dropper" with lore "&fFalling down and down, faster and faster until hiting something..."
            set slot 15 of {DJinv} to fire charge named "&cTerminate" with lore "&fKill the target..."
            set slot 16 of {DJinv} to redstone lamp named "&cOff" with lore "&fTurn the Lights off!"
            set slot 22 of {DJinv} to barrier named "&cClose"
            set slot 23 of {DJinv} to arrow named "&aNext Page"
            open {DJinv} to loop-player
            remove "FURDJ" from the scoreboard tags of loop-player
        else if loop-player has scoreboard tag "FURMUSIC":
            set {MUSICinv} to chest inventory with 3 rows named "{@sfont}Fur{@mfont}Music"
            set slot 11 of {MUSICinv} to pink concrete named "&dJoin us for a bite - JT Music" with lore "&fSister Location Remix, where she will consume u..."
            set slot 12 of {MUSICinv} to light blue concrete named "{@sfont}Fur{@mfont}Plex Main Theme" with lore "&fThe Main rocking theme of the {@sfont}Fur{@mfont}Plex"
            set slot 13 of {MUSICinv} to red concrete named "&cFive Night's at FurPlex" with lore "&fFive Night's at our home, our place and our rules..."
            set slot 14 of {MUSICinv} to purple concrete named "&5It's been so long" with lore "&fThe slaughter house between the Arcades of the Plex..."
            set slot 15 of {MUSICinv} to lime concrete named "&aWonderwall" with lore "&fToday is gonna be the day... bitch"
            set slot 21 of {MUSICinv} to arrow named "&aPrevious Page"
            set slot 22 of {MUSICinv} to barrier named "&cClose"
            set slot 23 of {MUSICinv} to note block named "&cStop Sounds"
            open {MUSICinv} to loop-player
            remove "FURMUSIC" from the scoreboard tags of loop-player
on inventory click:
    if name of event-inventory is "{@sfont}Fur{@mfont}DJ Menu":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        if event-item is twisting vines:
            add "DJ1" to the scoreboard tags of player
        if event-item is tnt:
            add "DJ2" to the scoreboard tags of player
        if event-item is iron sword:
            add "DJ3" to the scoreboard tags of player
        if event-item is ender pearl:
            add "DJ4" to the scoreboard tags of player
        if event-item is hopper:
            add "DJ5" to the scoreboard tags of player
        if event-item is fire charge:
            add "DJ6" to the scoreboard tags of player
        if event-item is redstone lamp:
            add "DJ7" to the scoreboard tags of player
        if event-item is arrow:
            close event-player's inventory
            open {MUSICinv} to player
    else if name of event-inventory is "{@sfont}Fur{@mfont}Music":
        cancel event
        if event-item is barrier named "&cClose":
            close event-player's inventory
        else if event-item is lime concrete:
            make player execute command "stopsound @a[distance=..15]"
            make player execute command "playsound music_disc.11 master @a[distance=..15] ~ ~ ~ 0.7"
        else if event-item is pink concrete:
            make player execute command "stopsound @a[distance=..15]"
            make player execute command "playsound music_disc.blocks master @a[distance=..15] ~ ~ ~ 0.69"
        else if event-item is light blue concrete:
            make player execute command "stopsound @a[distance=..15]"
            make player execute command "playsound music_disc.cat master @a[distance=..15] ~ ~ ~ 0.8"
        else if event-item is red concrete:
            make player execute command "stopsound @a[distance=..15]"
            make player execute command "playsound music_disc.strad master @a[distance=..15] ~ ~ ~ 1"
        else if event-item is purple concrete:
            make player execute command "stopsound @a[distance=..15]"
            make player execute command "playsound music_disc.mall master @a[distance=..15] ~ ~ ~ 0.7"
        else if event-item is note block:
            make player execute command "stopsound @a[distance=..15]"
        else if event-item is arrow:
            close event-player's inventory
            open {DJinv} to event-player
on right click:
    if name of event-item is "&6Furenta":
        if {drink.%event-item%.%player%} is 5:
            remove 1 of event-item from player
            set {drink.%event-item%.%player%} to 0
        add 1 to {drink.%event-item%.%player%}
        cancel event
        loop 360 times:
            set {_pl} to location of player
            set {_v} to spherical vector with radius 2, yaw loop-value-1 and pitch 0
            make 0 of dust using dustTransition(orange, orange, 1.4) at location 0.2 meter above {_pl} ~ {_v} with offset vector(0, 0, 0) with extra 0
        apply speed 1 to player for 5 seconds
        apply regeneration 1 to player for 3 seconds
        apply night vision 1 to player for 5 seconds
        wait 5 seconds
    if name of event-item is "&dFur Purr":
        if {drink.%event-item%.%player%} is 5:
            remove 1 of event-item from player
            set {drink.%event-item%.%player%} to 0
        add 1 to {drink.%event-item%.%player%}
        cancel event
        loop 360 times:
            set {_pl} to location of player
            set {_v} to spherical vector with radius 2, yaw loop-value-1 and pitch 0
            make 0 of dust using dustTransition(red, red, 1.4) at location 0.2 meter above {_pl} ~ {_v} with offset vector(0, 0, 0) with extra 0
        apply speed 1 to player for 3 seconds
        apply regeneration 2 to player for 3 seconds 
        apply night vision 1 to player for 5 seconds
        apply strength 1 to player for 3 seconds
        wait 5 seconds
